### ISSUE TITLE
Second instance of kruize doesn't show any recommendations

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#118]
Launched a couple of instances of kruize (docker containers) but the second instance, showed all recommendations as 0. Docker logs had the below exceptions:

java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at com.kruize.util.HttpUtil.getDataFromURL(HttpUtil.java:54)
        at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:192)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:253)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:220)
        at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:141)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-3" java.lang.NullPointerException
        at java.base/java.io.StringReader.<init>(Unknown Source)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:195)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:253)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:220)
        at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:141)
        at java.base/java.lang.Thread.run(Unknown Source)
2020-04-16 08:40:23.839:INFO::main: Logging initialized @1410ms to org.eclipse.jetty.util.log.StdErrLog

**Comment by chandrams** [comment]
Commands to run:

_>>./deploy.sh -ac docker -i chandra25ms/kruize:0.6.5_

second kruize using the below command:

_docker run -d --rm --name=kruize1     -p 31316:31313          --net=kruize-network --env CLUSTER_TYPE=DOCKER --env MONITORING_AGENT_ENDPOINT=http://localhost:9090 --env MONITORING_AGENT=Prometheus -v /home/chandrams/kruize/manifests/docker/kruize-docker.json:/opt/app/kruize-docker.json chandra25ms/kruize:0.6.5_

**Comment by chandrams** [comment]
At times, I see NPE too.

```java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at com.kruize.util.HttpUtil.getDataFromURL(HttpUtil.java:54)
        at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:192)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:253)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:220)
        at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:141)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-3" java.lang.NullPointerException
        at java.base/java.io.StringReader.<init>(Unknown Source)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:195)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:253)
        at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:220)
        at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:141)
        at java.base/java.lang.Thread.run(Unknown Source)
2020-04-20 06:43:24.558:INFO::main: Logging initialized @1368ms to org.eclipse.jetty.util.log.StdErrLog
```

**Comment by dinogun** [comment]
Currently since we dont support multiple instances of kruize running, I would suggest that kruize can check if one instance is already running and exit if it finds one.
