### ISSUE TITLE
kruize recommendations from ICP runs are 0

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#129]
**Describe the bug**
kruize recommendations from ICP runs are 0

**To Reproduce**
Steps to reproduce:
_Clone the kruize repo and cd kruize
./deploy.sh -ac icp -i chandra25ms/kruize:0.6.6 -k <ICP url>   -u <user> -p <password> -n <namespace>_

**Expected behavior**
Recommendations on resources used should be generated 

**Screenshots**
```
kubectl logs kruize-7fbb877845-kpjgt
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[20-May-06 15:21:21:457] [INFO] - Cluster Type: KUBERNETES
[20-May-06 15:21:21:464] [INFO] - Kubernetes Type: ICP
[20-May-06 15:21:21:464] [INFO] - Auth Type: OIDC
[20-May-06 15:21:21:464] [INFO] - Monitoring Agent: PROMETHEUS
[20-May-06 15:21:21:465] [INFO] - Monitoring agent service:


[20-May-06 15:21:21:465] [INFO] - End of initialization phase
[20-May-06 15:21:38:465] [INFO] - Using default labels
2020-05-06 15:21:39.363:INFO::main: Logging initialized @19055ms to org.eclipse.jetty.util.log.StdErrLog
[20-May-06 15:22:39:815] [INFO] - No previous data available for another-apps
[20-May-06 15:22:53:965] [INFO] - No previous recommendations available for another-apps
[20-May-06 15:23:01:582] [INFO] - No previous recommendations available for another-apps
[20-May-06 15:23:19:359] [INFO] - No previous recommendations available for another-apps
[20-May-06 15:23:42:873] [INFO] - No previous recommendations available for another-apps
[20-May-06 15:24:00:068] [INFO] - No previous data available for kruize
[20-May-06 15:24:01:849] [INFO] - No previous recommendations available for kruize
[20-May-06 15:24:14:726] [INFO] - No previous recommendations available for kruize
[20-May-06 15:24:24:680] [INFO] - No previous recommendations available for kruize
[20-May-06 15:24:35:406] [INFO] - No previous recommendations available for kruize
[20-May-06 15:24:46:054] [INFO] - No previous data available for acmeair-sample
[20-May-06 15:24:55:382] [INFO] - No previous recommendations available for acmeair-sample
[20-May-06 15:25:05:332] [INFO] - No previous recommendations available for acmeair-sample
[20-May-06 15:25:19:874] [INFO] - No previous recommendations available for acmeair-sample
[20-May-06 15:25:28:007] [INFO] - No previous recommendations available for acmeair-sample
[20-May-06 15:25:32:563] [INFO] - No previous data available for nodejs-express-demo1
[20-May-06 15:25:43:771] [INFO] - No previous recommendations available for nodejs-express-demo1
[20-May-06 15:26:01:369] [INFO] - No previous recommendations available for nodejs-express-demo1
[20-May-06 15:26:12:534] [INFO] - No previous recommendations available for nodejs-express-demo1
[20-May-06 15:26:20:913] [INFO] - No previous recommendations available for nodejs-express-demo1
[20-May-06 15:26:36:190] [INFO] - No previous data available for demo-appsodyapplication-on-icp
[20-May-06 15:26:40:302] [INFO] - No previous recommendations available for demo-appsodyapplication-on-icp
[20-May-06 15:26:45:639] [INFO] - No previous recommendations available for demo-appsodyapplication-on-icp
[20-May-06 15:26:57:165] [INFO] - No previous recommendations available for demo-appsodyapplication-on-icp
[20-May-06 15:27:00:908] [INFO] - No previous recommendations available for demo-appsodyapplication-on-icp
[20-May-06 15:27:09:137] [INFO] - No previous data available for appsody-app
[20-May-06 15:27:18:017] [INFO] - No previous data available for appsody-app
[20-May-06 15:27:32:271] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:27:39:806] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:27:43:738] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:27:52:256] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:28:03:938] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:28:15:344] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:28:30:393] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:28:34:754] [INFO] - No previous recommendations available for appsody-app
[20-May-06 15:28:48:864] [INFO] - another-apps is in idle state. Recommendations will be generated after it becomes active.
[20-May-06 15:28:48:865] [INFO] - another-apps-dc8fb77f7-d6fcm: CPU Limit = 0.0
[20-May-06 15:28:48:866] [INFO] - another-apps-dc8fb77f7-d6fcm: CPU Requests = 0.0
[20-May-06 15:28:48:866] [INFO] - another-apps-dc8fb77f7-d6fcm: Memory Limit = 0.0 MB
[20-May-06 15:28:48:867] [INFO] - another-apps-dc8fb77f7-d6fcm: Memory Requests = 0.0 MB

[20-May-06 15:28:54:919] [INFO] - kruize is in idle state. Recommendations will be generated after it becomes active.
[20-May-06 15:28:54:919] [INFO] - kruize-7fbb877845-kpjgt: CPU Limit = 0.0
[20-May-06 15:28:54:919] [INFO] - kruize-7fbb877845-kpjgt: CPU Requests = 0.0
[20-May-06 15:28:54:919] [INFO] - kruize-7fbb877845-kpjgt: Memory Limit = 0.0 MB
[20-May-06 15:28:54:920] [INFO] - kruize-7fbb877845-kpjgt: Memory Requests = 0.0 MB

[20-May-06 15:29:16:621] [INFO] - acmeair-sample is in idle state. Recommendations will be generated after it becomes active.
[20-May-06 15:29:16:623] [INFO] - acmeair-sample-65897bb6dd-zqkkx: CPU Limit = 0.0
[20-May-06 15:29:16:623] [INFO] - acmeair-sample-65897bb6dd-zqkkx: CPU Requests = 0.0
[20-May-06 15:29:16:624] [INFO] - acmeair-sample-65897bb6dd-zqkkx: Memory Limit = 0.0 MB
[20-May-06 15:29:16:625] [INFO] - acmeair-sample-65897bb6dd-zqkkx: Memory Requests = 0.0 MB
```

```
[
{
"application_name": "kruize",
"resources": {
"requests": {
"memory": "0.0MB",
"cpu": 0.0
},
"limits": {
"memory": "0.0MB",
"cpu": 0.0
}
}
},
{
"application_name": "acmeair-sample",
"resources": {
"requests": {
"memory": "0.0MB",
"cpu": 0.0
},
"limits": {
"memory": "0.0MB",
"cpu": 0.0
}
}
},
{
"application_name": "nodejs-express-demo1",
"resources": {
"requests": {
"memory": "0.0MB",
"cpu": 0.0
},
"limits": {
"memory": "0.0MB",
"cpu": 0.0
}
}
},
]
```

**Environment (please complete the following information):**
 - OS: ubuntu
 - Kubernetes Environment ICP

**Additional context**

**Comment by ShishirH** [comment]
Recommendations were zero on ICP until load was applied. Checking if no load cases on OpenShift and Minikube do not generate recommendations.

**Comment by chandrams** [comment]
I have checked without load on minikube and openshift, I see recommendations generated for acmeair.

**Comment by ShishirH** [comment]
Can you please post the minikube logs?

**Comment by chandrams** [comment]
With ICP I see this error while deploying kruize, tested with both old and new ICP setup:

```
[20-Jun-09 06:46:26:906] [INFO] - Cluster Type: KUBERNETES
[20-Jun-09 06:46:26:914] [INFO] - Kubernetes Type: ICP
[20-Jun-09 06:46:26:914] [INFO] - Auth Type: OIDC
[20-Jun-09 06:46:26:915] [INFO] - Monitoring Agent: PROMETHEUS
[20-Jun-09 06:46:26:915] [INFO] - Monitoring agent service:


[20-Jun-09 06:46:26:915] [INFO] - End of initialization phase
io.kubernetes.client.ApiException: Forbidden
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
        at io.kubernetes.client.apis.CoreV1Api.listServiceForAllNamespacesWithHttpInfo(CoreV1Api.java:19821)
        at io.kubernetes.client.apis.CoreV1Api.listServiceForAllNamespaces(CoreV1Api.java:19799)
        at com.kruize.environment.kubernetes.KubernetesEnvImpl.checkMonitoringAgentRunning(KubernetesEnvImpl.java:86)
        at com.kruize.environment.kubernetes.KubernetesEnvImpl.setupMonitoringAgent(KubernetesEnvImpl.java:67)
        at com.kruize.environment.EnvTypeImpl.getInstance(EnvTypeImpl.java:50)
        at com.kruize.environment.EnvTypeImpl.<clinit>(EnvTypeImpl.java:39)
        at com.kruize.collection.CollectMetrics.<init>(CollectMetrics.java:99)
        at com.kruize.main.Kruize.main(Kruize.java:41)
```

Got this error on one of the openshift setup (kruize-oc) but works fine on the other setup.
