### ISSUE TITLE
jlinked images fail with ssl handshake exception.

### ISSUE THREAD

**Issue by dinogun** [kruize/kruize#29]
jlinked docker images cause this exception when deployed to k8s
```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.kruize.collection.CollectMetrics.getDataFromURL(CollectMetrics.java:169)
	at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:274)
	at com.kruize.collection.CollectMetrics.getPreviousData(CollectMetrics.java:248)
	at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:136)
	at java.base/java.lang.Thread.run(Unknown Source)
Could not get previous data. Please check your prometheus version
https://192.168.122.156:8443/prometheus/api/v1/query?query=(kruize_exp_cpu_limits{application_name="kruize"}[2h])
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.kruize.collection.CollectMetrics.getDataFromURL(CollectMetrics.java:169)
	at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:274)
	at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:327)
	at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:302)
	at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:137)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-3" java.lang.NullPointerException
	at java.base/java.io.StringReader.<init>(Unknown Source)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.kruize.collection.CollectMetrics.getAsJsonArray(CollectMetrics.java:277)
	at com.kruize.collection.CollectMetrics.getPreviousKruizeData(CollectMetrics.java:327)
	at com.kruize.collection.CollectMetrics.getPreviousKruizeRecs(CollectMetrics.java:302)
	at com.kruize.collection.CollectMetrics.run(CollectMetrics.java:137)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by dinogun** [comment]
This is now fixed with #31
