### ISSUE TITLE
StringIndexOutOfBoundsException in parseApplicationName

### ISSUE THREAD

**Issue by ShishirH** [kruize/kruize#52]
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.base/java.lang.String.substring(Unknown Source)
    at com.kruize.environment.kubernetes.KubernetesEnvImpl.parseApplicationName(KubernetesEnvImpl.java:247)
    at com.kruize.environment.kubernetes.KubernetesEnvImpl.getPodMetrics(KubernetesEnvImpl.java:206)
    at com.kruize.environment.kubernetes.KubernetesEnvImpl.insertPodMetrics(KubernetesEnvImpl.java:177)
    at com.kruize.environment.kubernetes.KubernetesEnvImpl.getAllApps(KubernetesEnvImpl.java:164)
    at com.kruize.environment.EnvTypeImpl.getInstance(EnvTypeImpl.java:54)
    at com.kruize.environment.EnvTypeImpl.<clinit>(EnvTypeImpl.java:39)
```

Happens when the pod hash is not within the pod name.

**Comment by ShishirH** [comment]
```
$ oc describe kruize-65bc77ff6d-hphv2
error: the server doesn't have a resource type "kruize-65bc77ff6d-hphv2"
[dino@spinlock kruize]$ oc describe pod kruize-65bc77ff6d-hphv2
Name:               kruize-65bc77ff6d-hphv2
Namespace:          openshift-monitoring
Priority:           0
PriorityClassName:  <none>
Node:               rhos11-master.fyre.ibm.com/9.199.148.56
Start Time:         Wed, 27 Nov 2019 15:17:32 +0530
Labels:             app=kruize
                    app.kubernetes.io/name=kruize
                    name=kruize
                    pod-template-hash=2167339928
```
